version: "3.7"
services:
  # Redis - result backend
  redis:
    image: redis:alpine
  # RabbitMQ - queue
  rabbit:
    hostname: rabbit
    image: rabbitmq:3-management
    environment:
      - DEFAULT_USER=admin
      - DEFAULT_PASS=mypass
    ports:
      - "5672:5672"  
      - "15672:15672"  # here, we can access rabbitmq management plugin
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db

  front:
    restart: always
    build:
      context: ./front
    image: node:12.22.12
    volumes:
      - "./front:/app"
  
  # Django web server
  web:
    restart: always
    build:
      context: ./back
    hostname: web
    volumes:
      - ./back:/app
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - "8000:8000"
    depends_on:
        - db 
        - redis
    links:
      - rabbit
      - redis
    env_file:
      - ./.env
volumes:
  postgres_data:
  static_volume:
  media_volume: