# Generated by Django 3.1.5 on 2023-06-26 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20230626_1730'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='usertestresult',
        #     name='ip_address',
        #     field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ip Adres'),
        # ),
        migrations.AddField(
            model_name='usertestresult',
            name='overall_ball',
            field=models.FloatField(default=0, verbose_name='Umumiy bal'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='grade_per_question',
            field=models.FloatField(default=0, verbose_name='Bal'),
        ),
    ]
